/***************************************************************************
 *                                                                         *
 * Auto Generated BY CodeComment                                           *
 * Copyright(C) 2000-2016, JiangSu Yinhe Electronic Co.Ltd.                *
 * All Rights Reserved.                                                    *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Yinhe Elec Co.Ltd.       *
 * The copyright notice above does not evidence any actual or intended     *
 * publication of such source code.                                        *
 *                                                                         *
 **************************************************************************/
package com.lip.demo.data;

import java.util.List;

/** 
* @ClassName: BaseRepository
* @Description: 增删改查基类
* @author lipeng32768@163.com
* @date 2016年8月10日 下午2:06:52  
* @version v1.0.0
 */
public interface BaseRepository <T>{
		
		// 根据id查找
		public T findById(Number id) ;
		// 增加
		public void addEntity(T entity) ;
		// 更新
		public void updateEntity(T entity);
		
		public int countEntities(List<Long> idList) ;
		
		public int deleteEntities(List<Long> idList);
		
		public void deleteEntity(T entity);
		
		public void deleteEntity(Number id);
		
		public List<T> findAllOrderedById() ;
		
		public void clearEntity();
}
