/***************************************************************************
 *                                                                         *
 * Auto Generated BY CodeComment                                           *
 * Copyright(C) 2000-2016, JiangSu Yinhe Electronic Co.Ltd.                *
 * All Rights Reserved.                                                    *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Yinhe Elec Co.Ltd.       *
 * The copyright notice above does not evidence any actual or intended     *
 * publication of such source code.                                        *
 *                                                                         *
 **************************************************************************/

package com.lip.demo.data;

import com.lip.demo.model.Users;

/**  
* @ClassName: UsersRepository
* @Description: TODO 
* @author lipeng32768@163.com
* @date 2016年8月9日 上午4:41:15  
* @version v1.0.0
*/

public interface UsersRepository extends BaseRepository<Users> {

	public Users findUserByPhoneNumber(String phoneNumber);

	public Users findUserByName(String name);


}
